import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient, createAdminSupabaseClient } from '@/lib/supabase/server'

interface RouteParams {
  params: { id: string }
}

export async function POST(_request: NextRequest, { params }: RouteParams) {
  try {
    const supabase = createServerSupabaseClient()

    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json(
        { error: 'Vous devez être connecté.' },
        { status: 401 }
      )
    }

    // Verify ownership and current status
    const { data: formation, error: formationError } = await supabase
      .from('formations')
      .select('id, statut')
      .eq('id', params.id)
      .eq('formateur_id', user.id)
      .single()

    if (formationError || !formation) {
      return NextResponse.json(
        { error: 'Formation introuvable ou accès refusé.' },
        { status: 404 }
      )
    }

    if (formation.statut !== 'brouillon') {
      return NextResponse.json(
        { error: 'Seules les formations en brouillon peuvent être activées.' },
        { status: 400 }
      )
    }

    // 1. Set statut to 'active'
    const { error: updateError } = await supabase
      .from('formations')
      .update({ statut: 'active' })
      .eq('id', params.id)

    if (updateError) {
      console.error('Erreur activation formation:', updateError)
      return NextResponse.json(
        { error: "Erreur lors de l'activation de la formation." },
        { status: 500 }
      )
    }

    // 2. Fetch all messages and participants
    const [{ data: messages }, { data: participants }] = await Promise.all([
      supabase
        .from('messages_planifies')
        .select('id')
        .eq('formation_id', params.id),
      supabase
        .from('participants')
        .select('id')
        .eq('formation_id', params.id),
    ])

    if (!messages || !participants) {
      return NextResponse.json(
        { error: 'Erreur lors de la récupération des données.' },
        { status: 500 }
      )
    }

    // 3. Generate envois_participants (one per participant per message)
    const envoisInserts = messages.flatMap((message) =>
      participants.map((participant) => ({
        message_id: message.id,
        participant_id: participant.id,
        // token will be generated by the DB default (gen_random_uuid())
        token: crypto.randomUUID(),
        statut: 'en_attente' as const,
        quiz_complete: false,
      }))
    )

    if (envoisInserts.length === 0) {
      return NextResponse.json(
        { error: `Aucun envoi à créer. Messages: ${messages.length}, Participants: ${participants.length}` },
        { status: 400 }
      )
    }

    if (envoisInserts.length > 0) {
      const adminSupabase = createAdminSupabaseClient()
      const { error: envoisError } = await adminSupabase
        .from('envois_participants')
        .insert(envoisInserts)

      if (envoisError) {
        console.error('Erreur création envois:', envoisError)
        // Revert statut to brouillon
        await supabase
          .from('formations')
          .update({ statut: 'brouillon' })
          .eq('id', params.id)

        return NextResponse.json(
          { error: 'Erreur lors de la génération des envois.', details: envoisError },
          { status: 500 }
        )
      }
    }

    return NextResponse.json({
      message: 'Formation activée avec succès.',
      envois_crees: envoisInserts.length,
    })
  } catch (err) {
    console.error('Erreur inattendue activation:', err)
    return NextResponse.json(
      { error: 'Une erreur inattendue est survenue.' },
      { status: 500 }
    )
  }
}
